### PR TITLE
fix for updating lua file

### PR DESCRIPTION
**Pull request by yama2akira**
When I edit a lua file which is already asseted, the update could not applied to the asset with the current repository. So I'd implemented the remport process. I hope you review the code.

### CODE REVIEW

**Comment by rdeioris** [comment]
@yama2akira thanks a lot, looks good. can you add your credits on top of the functions ?

**Comment by yama2akira** [comment]
OK, however I don't know what to "add my credit". would you show me some examples?

**Comment by rdeioris** [comment]
On the second line of the file (after the first copyright comment) add something like

/* Reimport system by yama2akira (Name Surname) */

**Comment by yama2akira** [comment]
I've added my credit

**Comment by yama2akira** [comment]
Thank you!

**Pull request merged**
